name: Contracts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
      - name: Install Foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run foundry node, deploy contracts (& generate contracts typescript output)
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn chain & yarn deploy

  contracts-lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
      - name: Run foundry lint
        run: yarn foundry:lint --check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
      - name: Run Forge tests
        run: yarn foundry:test -vvv
